### ISSUE TITLE
POST transaction smart receipt data

### ISSUE THREAD

**Issue by pl4nty** [up-banking/api#100]
AfterPay is currently supported for itemised receipts, but other vendors aren't as far as I know. If receipts could be added via the API, the community could create third-party integrations eg Everyday Rewards, Flybuys, PayPal, etc.

This would be a compelling alternative to the Big 4, who have been backing [Slyp](www.slyp.com.au) with little progress and no public API.

**Comment by markbrown4** [comment]
Thanks! Have raised the question with our product team.
I'd like to see smart receipts get some more love, it could give people a lot more insight into their spending.
I think we'd most likely add the capabilities in the app first, before adding to the API.
