### ISSUE TITLE
✨ Add transaction icon URLs

### ISSUE THREAD

**Issue by Hona** [up-banking/api#101]
Currently displaying transactions in a table is really ugly without the images like in the app.

**Comment by Hona** [comment]
For example, we could do a lot nicer than this: 

![image](https://user-images.githubusercontent.com/10430890/154388459-6b8080fa-fd68-4108-9c9d-b084023027c5.png)

**Comment by markbrown4** [comment]
Adding as a duplicate of exposing merchant logo https://github.com/up-banking/api/issues/64
