### ISSUE TITLE
GET Transactions based on Date Range

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#105]
Hi folks, I was hoping to get transaction detail by specific date ranges?

I have a current setup that runs thru all the pages and then dumps the JSON into a raw file for me to use within excel.
However, as time has gone on, the requests are getting too big and will time out. To the point where my setup no longer works.

If I can set up calls based on date ranges, I can then download history much easier and update current periods.

My idea is to roll thru each quarterly period once, save off the history, then update the current quarter only until it has passed and fully settled.

I cannot see how to restrict my min/max dates within my calls.

(This might be a feature request)

**Comment by d11wtq** [comment]
Hi @gxander85,

Do `filter[since]` and `filter[until]` not help you? Those are for filtering by date/time.

https://developer.up.com.au/#transactions

Be sure to correctly URL encode those values as they contain `:` and `+` characters, which are not URL safe and need to be percent-encoded.
