### ISSUE TITLE
2up tags aren't working as expected

### ISSUE THREAD

**Issue by sensible-s** [up-banking/api#112]
Expected behaviour:
I hit the /tags endpoint and expect to see a list of all tags across my up and 2up accounts.

Actual behaviour:
- The tags endpoint only returns tags on transactions I authorised. If my 2up person paid for something and I tag it, it doesn't appear in the list
- My 2up person can't see any tag I create

Note, I can successfully filter transactions by tag manually through the transactions endpoint.

**Comment by markbrown4** [comment]
@sensible-s 2Up tags are now available.  Thanks for raising!
