### ISSUE TITLE
Receiving 'Invalid Parameter' for a valid rfc-3339 date using filter[since]

### ISSUE THREAD

**Issue by robase** [up-banking/api#116]
Hitting issues when attempting to filter transactions from the `/transactions` endpoint by date using `filter[since]` with a timestamp that has a positive timezone offset. 

running:
```bash
curl https://api.up.com.au/api/v1/transactions \
  -G \
  -H 'Authorization: Bearer <token>' \
  -d 'filter[since]=2022-09-14T10:23:50+10:00'
```

returns:
```json
{
  "errors": [
    {
      "status": "400",
      "title": "Invalid Parameter",
      "detail": "invalid date-time value (must be rfc-3339)",
      "source": {
        "parameter": "filter[since]"
      }
    }
  ]
}
```

This example uses a date value from an [example](https://developer.up.com.au/#transactions) provided in the docs

The param works fine if using `Z` or a negative offset e.g `-10:00` does work but `+10:00` doesn't

**Comment by joshsimonis** [comment]
I'm also running into this issue. Seems to be an issue with the encoding of the '+' character - seems to be incorrectly url encoded as %2 instead of %2B.
If a already encoded url is shot through with %2B, this works fine, but if a raw + is sent it is being incorrectly interpreted.

**Comment by mcclown** [comment]
I'm still seeing this issue with the API today.

https://api.up.com.au/api/v1/transactions?filter[since]=2023-08-01T00:00:00%2B10:00 works.

https://api.up.com.au/api/v1/transactions?filter[since]=2023-08-01T00:00:00+10:00 fails with the same error as above.

**Comment by markbrown4** [comment]
This can be surprising but query params do need to be correctly URL Encoded.  We've tried to call this out in the docs at the end of the Query Parameters section.

<img width="589" alt="Screenshot 2024-03-20 at 5 09 45 PM" src="https://github.com/up-banking/api/assets/140878/e0254fa9-5dac-4d5f-a420-b359ab4cb530">
