### ISSUE TITLE
Getting Unauthorised

### ISSUE THREAD

**Issue by pramish** [up-banking/api#12]
<img width="1092" alt="Screen Shot 2020-07-28 at 15 47 33" src="https://user-images.githubusercontent.com/26316094/88624051-a7d60580-d0e9-11ea-9bc3-0839f2e1a8b2.png">

### Even I put my bearer token, I can't achieve this.

Please help me out.

**Comment by illusional** [comment]
Is there a colon between the Authorization and Bearer, eg: `Authorization: Bearer`. Can't see from the screenshot.

**Comment by pramish** [comment]
> Is there a colon between the Authorization and Bearer, eg: `Authorization: Bearer`. Can't see from the screenshot.

There isn't.

**Comment by yogeshpathade** [comment]
@pramish Have a look at this issue #1 If you had multiple tabs open with the page to get the access token https://api.up.com.au/getting_started then you probably have a the token you are using revoked. Make sure you have only one page open when you get the token.

**Comment by pramish** [comment]
Thanks @yogeshpathade for your help. I was actually using the revoked token.
