### ISSUE TITLE
Feature Request: Be able to match a contribution in a two up account

### ISSUE THREAD

**Issue by gregless22** [up-banking/api#120]
Have the ability to match a contribution.  For example... when my partner puts $20 on our joint account.  I should be able to select the transaction and click "Match Contribution". Which would then prompt me "where from" with my up account set as default.  Works similarly to "Cover this transaction"

**Comment by markbrown4** [comment]
Hey, thanks for the feedback!
Closing as this is more of an app feature request, rather than a request for the developer API.
