### ISSUE TITLE
Feature Request: Include savers goal amount in Accounts API response

### ISSUE THREAD

**Issue by njohnstone2** [up-banking/api#121]
The API response for the Accounts endpoint returns the current amount in an account but it would be useful if it would return additional info on the account. Specifically I would like to know the savings goal amount for each of the savers returned in the response.

Current mock response:
```
{
    "data": {
        "type": "accounts",
        "id": "***",
        "attributes": {
            "displayName": "Example",
            "accountType": "SAVER",
            "ownershipType": "INDIVIDUAL",
            "balance": {
                "currencyCode": "AUD",
                "value": "0.00",
                "valueInBaseUnits": 0
            },
        },
        ...
    }
}
```

Under the `attributes` object it would be useful to have an object similar to `balance`  that is used to track the savers goal.

**Comment by AussieEevee** [comment]
This is similar to #10

**Comment by njohnstone2** [comment]
You're right. Closing in favour of #10
