### ISSUE TITLE
Identifiable Transaction Owners

### ISSUE THREAD

**Issue by fourben** [up-banking/api#126]
I am currently working on ingesting our banking data into a home dashboard I’m building. I can’t see a way to differentiate my partners 2UP transactions from my own.

Potentially by assigning cards to the system and relying on the card number suffix, but it would be great to explicitly know.

Use case being rendering charts based on each of our spending categorisations and amounts.

Is this something that can be exposed in some way?

Cheers

**Comment by willem-h** [comment]
I’d also love to see this. I agree that using the last four from the card number would only be a partial solution. 

Like a few people around here I’m integrating my Up accounts with YNAB and want to notify each of us separately to confirm transactions as they arrive. The person who spent the money has the most context to easily confirm and categorise it.

**Comment by markbrown4** [comment]
Transactions will soon expose a "performingCustomer" with this e.g.

`"performingCustomer": { "displayName": "$mark" }`

It'll return either the Upname or preferred name.
