### ISSUE TITLE
Get more than 100 transactions and Filter on Tags

### ISSUE THREAD

**Issue by avinashkoduri** [up-banking/api#127]
Hi, I am new to programming. Learning how to use APIs.

Currently, I am using the following code to get the first 100 transactions and trying to filter by a particular Tag.
1. How do I get transactions outside the first 100? i.e. 100 - 200 transactions and so on.
2. Filter by Tags is not working. Is this even supported?

![image](https://github.com/up-banking/api/assets/48195565/e5d0741d-726c-46bd-ba3a-6361f17c9faa)

Thanks

**Comment by d11wtq** [comment]
Hi @avinashkoduri 

Great to see you're getting your feet wet and having a go with the Up API!

To get the next page of transactions, you need to follow the links return in the API response. There should be a `next` page URL listed, as long as there is a next page. If you request that URL then you should get the next page of transactions, and so on...

https://developer.up.com.au/#pagination

In terms of filtering by tags, I think your issue there will be that you need to use `filter[tag]`, not `filter[tags]`. Let me know if that still doesn't work for you.

**Comment by avinashkoduri** [comment]
Thank you very much @d11wtq

Your suggestions worked.
