### ISSUE TITLE
Suggestion: Community provided examples

### ISSUE THREAD

**Issue by ilievskizoran** [up-banking/api#13]
I think it would be cool if there was a folder in this repo, let's call it `/examples` where there are community submitted examples of how the API is being leveraged.

e.g
```
/examples
 /JS-android-widget-shortcut
 /RUBY-google-assistant-announcement
```

Thoughts?

Happy to start it off by providing a PR.

**Comment by levibuzolic** [comment]
I imagine it might be more practical to have a `Examples.md` with links to other repositories so each developer can maintain control and manage their example themselves.

**Comment by balupton** [comment]
It would be nice if this repo enabled the discussion tab, that way the ecosystem can discuss and help each other build ontop of it. Unless there is a discourse forum somewhere?

**Comment by balupton** [comment]
As an alternative to embedded examples, which is difficult to maintain and keep in sync - perhaps an `awesome-up` repo would be best?

**Comment by ilievskizoran** [comment]
Hello team up 👋
@d11wtq 

Any updates or progress on the examples branch being potentially merged into master?

**Comment by d11wtq** [comment]
Apologies @ilievskizoran. I did do some work to bring this in but just need a green light from the powers that be. Chasing it up for you today.

**Comment by d11wtq** [comment]
Ok, green light given. Will sort this now.

**Comment by d11wtq** [comment]
@ilievskizoran this is now in master. Thanks for doing this and apologies for the delay in getting it merged. I moved the document to community/EXAMPLES.md and reformatted it slightly. Future PRs can just target master.

**Comment by ilievskizoran** [comment]
@d11wtq Amazing. Thank you for moving this along quickly this morning.
