### ISSUE TITLE
Transactions endpoint to return notes field

### ISSUE THREAD

**Issue by aleayr** [up-banking/api#133]
Now that we can add notes to the transaction (via Up High currently), it would be great if we could have the notes fields returned against the transaction.

**Comment by markbrown4** [comment]
Transactions will soon expose a "note" field with this value. e.g.

`"note":  { "text": "my note" }`

I'm looking into exposing "attachments" as well separate to this.

**Comment by markbrown4** [comment]
Transactions return an optional "attachment" relationship.
They can be queried separately as a new resource.

```
GET /attachments
GET /attachments/{id}
``

Docs will update shortly.

**Comment by kailovel** [comment]
Awesome!

**Comment by kailovel** [comment]
Hey @markbrown4, firstly noting this is great progress, would you ever consider POST / PATCH for Notes, like Categories and Tags?

Usecase: I use a spreadsheet to review my transactions daily. I add context in a "Comment" field (like what I ordered, why I bought it etc.). If this went back into the Up note field, that would be wicked
