### ISSUE TITLE
Is the Up Bank API going to be expanded?

### ISSUE THREAD

**Issue by lewisdenny** [up-banking/api#135]
Hi Team, 

Just wondering if we can get an official response on weather the Up Bank API is going to be expanded upon? It's been a few years an nothing much has changed and GitHub issues go unanswered. 

Tagging you both, thanks for the great work so far, just want to know if things like creating transactions and other new Up features will be exposed by the API some time soon.
 
@d11wtq and @levibuzolic

**Comment by markbrown4** [comment]
Thanks for the question Lewis, has sparked a bit of discussion internally.
There is a desire to see the API progress.
I'll get on top of the unanswered issues so at least people know what to expect.

> just want to know if things like creating transactions and other new Up features will be exposed by the API some time soon.
Write operations like Transfers and Payments are not a current priority.
That's not to say it _won't_ happen, but you shouldn't expect it soon.

I can see some feature requests that we should be able to add support for.
Things like "Notes" and "Transaction Owner" for 2Up purchases would be great additions.

**Comment by markbrown4** [comment]
My current thinking is we should prioritise bug fixes and security issues, then fill out the core features:
- Additions to Transaction: Type, Deep link, Transacting Customer, Notes, Covers/Forwards
- Additions to Account:  BSB, Account number, Spendable Balance 
- Exposing Savers: Goal amount, emoji, name
- Exposing Merchant: Location, URL, Logo

Exposing Payments, Upcoming, Auto Transfers would be nice additions as well but haven't made the initial cut.
_Sending_ Payments and Transfers would open up a lot of potential for innovation.  We'd like to see it happen but these are not planned at this stage.

Hope that gives some clarity on what we're looking at doing in the short term.
If issues are raised here, we'll make sure to respond.

**Comment by lewisdenny** [comment]
Thanks for your response @markbrown4, I'm happy to hear the read only API is going to continue being maintained. 

Agree sending payments would open up a lot of potential for innovation and I hope that will be added to the road map in the future, it's quite a niche feature by Up Bank is a niche bank :)

**Comment by AdenMck** [comment]
@markbrown4 
> _Sending_ Payments and Transfers would open up a lot of potential for innovation. We'd like to see it happen but these are not planned at this stage.

Being able to automate transfers between savers and transaction account would be amazing, but I could see there being some security concerns around it, and especially sending payments to external accounts.

Super excited to hear about the potential addition of spendable balance, and notes.  Hopefully notes can be read/write?

**Comment by steveharrison** [comment]
As a first round of enhancements, would love Transaction Type and Location, URL, Logo for Merchants, @markbrown4. Trying to add a filter for BPAY payments, and noticed that the CSV indicates this but not the API.

**Comment by markbrown4** [comment]
Now that we're moving again I'm going to close this issue.

I'll update the change log with recent updates: https://github.com/up-banking/api/issues/31

We won't move at lightning speed with these updates, but I'll keep chipping away at them.

**Comment by lewisdenny** [comment]
Agreed, thanks for your work on this one mate <3
