### ISSUE TITLE
Generate token in app

### ISSUE THREAD

**Issue by HLB1797** [up-banking/api#137]
How do I get one

**Comment by markbrown4** [comment]
At the moment you can only get your access token at "Up > Scan a QR code" from a second device.
https://api.up.com.au/getting_started

However we are looking at being able to generate a token in app as soon as this week.

**Comment by WarrenTheRabbit** [comment]
That's exciting, @markbrown4. Are there any plans for allowing third parties to request, store and invalidate PATs on behalf of Up customers?

**Comment by markbrown4** [comment]
Not at this stage, these tokens are still intended for personal use only. We do support Open Banking though which does what you describe.
