### ISSUE TITLE
API Bugs

### ISSUE THREAD

**Issue by emansih** [up-banking/api#138]
Hello. I was playing around with the API and I have possibly found some bugs?

1. 
![HOMELOAN](https://github.com/up-banking/api/assets/5896415/f0e62c69-99f7-4224-bef3-3740d3890b9e)

When calling the `/v1/accounts` end point, I applied a `HOME_LOAN` filter and the API returns me both `TRANSACTIONAL` and `SAVER`  accout type. Is it working as intended?

Steps to produce: 
```
curl --location --globoff 'https://api.up.com.au/api/v1/accounts?filter[accountType]=HOME_LOAN' \
--header 'Authorization: Bearer XXXXXXXXX'
```

2.

When calling the `/v1/transactions` endpoint, I supplied a date that does not exist - 31 Feb 2024, the API returns me data in 1 March 2024. The API fails to return data if I supply 32 Feb 2024, which is working as intended.  

![Transaction](https://github.com/up-banking/api/assets/5896415/73326847-12d3-4d69-8e5d-df37b7e55b74)

Steps to reproduce: 

```
curl --location --globoff 'https://api.up.com.au/api/v1/transactions?filter[since]=2024-02-01T15%3A00%3A00.05%2B11%3A00&filter[until]=2024-02-31T15%3A00%3A00.05%2B11%3A00' \
--header 'Authorization: Bearer XXXX'
```
Returns a response with HTTP 200 OK. Note the filter[until] date is _2024-02-31_, which is impossible

```
curl --location --globoff 'https://api.up.com.au/api/v1/transactions?filter[since]=2024-02-01T15%3A00%3A00.05%2B11%3A00&filter[until]=2024-02-32T15%3A00%3A00.05%2B11%3A00' \
--header 'Authorization: Bearer XXXXX'
```
Returns a response with HTTP 400 Bad Request. This is working as intended as  the filter[until] date is _2024-02-32_ which  does not exist.

**Comment by markbrown4** [comment]
Thanks for raise, will get fixes for these deployed today.
