### ISSUE TITLE
Open Banking public endpoints

### ISSUE THREAD

**Issue by jasonsong93** [up-banking/api#139]
Hi team!

I'm just trying to get the list of all products as per CDR/Open Banking for /Products (the public one not requiring a PAT).
For some reason I keep getting server errors when attempting to reach the endpoint.

Any assistance would be appreciated.

**Comment by d11wtq** [comment]
How are you calling the API? It is up and working but you need to ensure you are passing the correct headers (`x-v`) as per the CDR specification.

Here is a valid initial request (using HTTPie):

```
http https://api.up.com.au/cds-au/v1/banking/products 'x-v: 3'
```

The equivalent with curl would be:

```
curl https://api.up.com.au/cds-au/v1/banking/products -H 'x-v: 3'
```

**Comment by jasonsong93** [comment]
Thanks for the help, this is my mistake. I had the API incorrect and was attempting to hit:
`https://api.up.com.au/public/cds-au/v1/banking/products` 

The reasoning was because Commonwealth Bank separates theirs with `public` as seen here:
https://www.commbank.com.au/developer/documentation/Products?ei=devportallanding_products
and I mistakenly assumed it was the case for all banks (when actually they're the outlier here).

Apologies and thanks for the help!
