### ISSUE TITLE
OpenApi validation fails with Azure API Management and apitools.dev

### ISSUE THREAD

**Issue by gitstua** [up-banking/api#14]
I tried to import the OpenAPI definition into Azure API Management consumption plan and this failed
also tried https://apitools.dev/swagger-parser/online/ and it suggested an error in the OpenAPI

The error presented by Azure APIM was:

>One or more fields contain incorrect values:
Parsing error(s): Data and type mismatch found. [#/paths/~1accounts/get/parameters/0/example] Data and type mismatch found. [#/paths/~1transactions/get/parameters/0/example] Data and type mismatch found. [#/paths/~1transactions/get/parameters/1/example] Data and type mismatch found. [#/paths/~1transactions/get/parameters/2/example] Data and type mismatch found. [#/paths/~1accounts~1{accountId}~1transactions/get/parameters/1/example] Data and type mismatch found. [#/paths/~1accounts~1{accountId}~1transactions/get/parameters/2/example] Data and type mismatch found. [#/paths/~1accounts~1{accountId}~1transactions/get/parameters/3/example] Data and type mismatch found. [#/paths/~1webhooks/get/parameters/0/example] Data and type mismatch found. [#/paths/~1webhooks~1{webhookId}~1logs/get/parameters/1/example]
Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).

**Comment by d11wtq** [comment]
This is interesting as we do validate the document, but only against the JSON schema for the OAS schema itself; not semantic validation.

I know why this will be happening and should be able to fix it up. Basically those examples have the query string syntax embedded in them for the benefit of our docs website and they shouldn't do (e.g. `?page[size]=30` vs simply `30`). We'll have to move some of that logic off to the documentation site itself.

Will sort it out and get back to you.

**Comment by gitstua** [comment]
no worries Chris, great to see the API. I just wanted to let you know so you could resolve at some stage :)

**Comment by d11wtq** [comment]
@gitstua I've pushed up a change that removes the `?xxx=yyy` stuff and just puts the value (with the correct data type) in the `example` field. Would you mind confirming this works now? Tested with https://apitools.dev/swagger-parser/online/ fine and validates against the OAS schema itself.

**Comment by gitstua** [comment]
I successfully loaded the definition into Azure API Management and called the api to list accounts. 

#notyouraverageinteractionwithabank

**Comment by d11wtq** [comment]
Legend, thanks for confirming ✨
