### ISSUE TITLE
403 Forbidden on "Get your Personal Access Token" CTA

### ISSUE THREAD

**Issue by kailovel** [up-banking/api#146]
Getting a 403 Forbidden when clicking on this button on https://developer.up.com.au/

<img width="304" alt="image" src="https://github.com/user-attachments/assets/0ad89a70-cec8-4a63-8de2-145f53343a88">

It takes me to https://api.up.com.au/

Via Google, I found https://api.up.com.au/getting_started which does seem to work.

**Comment by markbrown4** [comment]
Hmm, that's odd.
That's just a link to https://api.up.com.au which redirects to https://api.up.com.au/getting_started

No obvious reasons why you'd be seeing that.
Does it persist on a clean session?

**Comment by dcousens** [comment]
Cannot reproduce
