### ISSUE TITLE
Trying to process transactions

### ISSUE THREAD

**Issue by Mooshieblob1** [up-banking/api#149]
## **GitHub Issue Title:** Unable to Initiate Transactions

**Description:**
I'm unable to initiate transactions on my latest push to the `https://github.com/Mooshieblob1/finance-site.github.io` repository. Despite reviewing the documentation, I haven't found clear instructions on how to proceed.

**Steps to Reproduce:**
1. Navigate to the transaction page: Click on the "Transactions" link in the main navigation.
2. Select the desired transaction type: Choose the correct accounts to transfer from and to, and click send
3. Confirm transaction: Click on the "Transfer" button.

**Expected Behavior:**
Upon confirming the transaction, I should be prompted to enter my authentication credentials or receive a confirmation message indicating that the transaction has been initiated successfully.

**Actual Behavior:**
Instead, I encounter an error message stating "API Error: Not found"

**Additional Notes:**
* I've verified that my account has sufficient funds to cover the transaction.
* I've checked the network connection and confirmed that it's stable.
* I've tried clearing my browser cache and cookies.
* I've ensured that the API key is correct, it is able to fetch accounts and balances perfectly fine.

Please let me know if anyone has any insight on how to resolve this, thank you.

P.S for obvious reasons, my .env file is omitted. 
![image](https://github.com/user-attachments/assets/4ef63257-42b4-4a9a-b604-2fffe42f09c5)

**Comment by markbrown4** [comment]
Hi,

It's not possible to make transfers / payments yet with the Up API.
We would like to support these features, but it's not currently in the planned features for the short term.

They have been requested though:
https://github.com/up-banking/api/issues/132
https://github.com/up-banking/api/issues/16

The supported features are documented here: https://developer.up.com.au/
