### ISSUE TITLE
Transaction Filters - 'Since' and 'Until' failing w/ invalid date-time value

### ISSUE THREAD

**Issue by darrenjrobinson** [up-banking/api#15]
Using filters [since] and [until] returns "invalid date-time value (must be rfc-3339)"

Example as per RFC-3339
```
VERBOSE: GET https://api.up.com.au/api/v1/transactions?filter[since]=2020-07-27T09:07:54+10:00z with 0-byte payload
VERBOSE: received -byte response of content type application/json
Get-UpBankTransactions: {"errors":[{"status":"400","title":"Invalid Parameter","detail":"invalid date-time value (must be rfc-3339)","source":{"parameter":"filter[since]"}}]}
```

Example omitting Z from datetime value

```
VERBOSE: GET https://api.up.com.au/api/v1/transactions?filter[until]=2020-07-27T09:07:54+10:00 with 0-byte payload
VERBOSE: received -byte response of content type application/json
Get-UpBankTransactions: {"errors":[{"status":"400","title":"Invalid Parameter","detail":"invalid date-time value (must be rfc-3339)","source":{"parameter":"filter[until]"}}]}
```

**Comment by darrenjrobinson** [comment]
Progress. The API isn't accepting timezone offsets.
This works

```
VERBOSE: GET https://api.up.com.au/api/v1/transactions?filter[until]=2020-07-27T09:07:54Z with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: utf-8
```

and combined with page size
```
VERBOSE: GET https://api.up.com.au/api/v1/transactions?page[size]=10&filter[since]=2020-07-27T09:07:54Z with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: utf-8
```

**Comment by d11wtq** [comment]
Are you correctly URI encoding the timestamp? The API definitely accepts those values, but `+` in particular does need to be encoded otherwise it's received as ` ` (space).

**Comment by d11wtq** [comment]
To clarify,

```

?filter[since]=2020-07-27T09:07:54+10:00z
```

To my knowledge, the trailing z here is not valid. The time zone is either specified as just `Z` or `+HH:MM`, or `-HH:MM`, but not both.

These should both be valid (provided they are URI escaped:

```
?filter[since]=2020-07-27T09:07:54+10:00

?filter[since]=2020-07-27T09:07:54Z
```

In the docs we are presenting examples with the above syntax for readability. Correctly encoded this would be difficult to read:

```
?filter%5Bsince%5D=2020-07-27T09%3A07%3A54%2B10%3A00
```

We should absolutely call out in the docs that these values need to be URI encoded before sending to the server. Will look to sort that out 📖

**Comment by darrenjrobinson** [comment]
Thx @d11wtq 
Here is the twist, using the default method (in PowerShell) to URL Encode the query params the output looks like this;
```
?filter%5bsince%5d%3d2020-07-27T09%3a07%3a54%2b10%3a00
```
This fails against the Up Bank API.
If I convert the URL Encoded params to UpperCase e.g
```
(Get-Culture).TextInfo.ToUpper($queryEncoded)
```
to get 
```
?FILTER%5BSINCE%5D%3D2020-07-27T09%3A07%3A54%2B10%3A00
```
everything works as expected.

So, the issue was two fold. One the query params must be encoded/escaped AND they must be in UpperCase.

**Comment by darrenjrobinson** [comment]
Actually, I might have jumped too soon @d11wtq 

Whilst the query will now submit and results returned the criteria is not respected.

Example: Query for transactions SINCE 27/7/2020 will return transactions before 27/7/2020.
Example  2: Query for transactions SINCE 27/7/2020 with a pageSize of 1 and 20 were returned.

More debugging required on both ends I think.

**Comment by d11wtq** [comment]
I think you want `until`. Results are ordered time descending, since `since` won't come into play without `until`.

**Comment by d11wtq** [comment]
Just testing the lowercase encoding and it works for me. The percent-encoding is not case sensitive, but the parameter names are case sensitive though, so `FILTER` would not be understood. Also the `=` should not be encoded. Not sure if that was just a mistake in the examples you gave above, or if they were sent in the request that way.

**Comment by darrenjrobinson** [comment]
Ok, finally success.
This maybe a PowerShell thing, but chances are it is relevant to other languages.
PowerShell will URLEncode '=' and '&' which means the Up Bank API will just ignore the filters even though it see's you're trying to do something. 

A bit of manipulation and the following example requests are working as expected;

```
Get-UpBankAccountTransactions -accountID $myAccounts[1].id -since 2020-07-08T01:02:03+10:00 -verbose
VERBOSE: GET https://api.up.com.au/api/v1/accounts/<accountID>/transactions?filter%5Bsince%5D=2020-07-08T01%3A02%3A03%2B10%3A00 with 0-byte payload


Get-UpBankAccountTransactions -accountID $myAccounts[1].id -until 2020-07-27T01:02:03+10:00 -verbose
VERBOSE: GET https://api.up.com.au/api/v1/accounts/<accountID>/transactions?filter%5Buntil%5D=2020-07-27T01%3A02%3A03%2B10%3A00 with 0-byte payload

Get-UpBankAccountTransactions -accountID $myAccounts[1].id -since 2020-07-08T01:02:03+10:00 -pageSize 5 -verbose
VERBOSE: GET https://api.up.com.au/api/v1/accounts/<accountID>/transactions?page%5Bsize%5D=5&filter%5Bsince%5D=2020-07-08T01%3A02%3A03%2B10%3A00 with 0-byte payload
```

**Comment by d11wtq** [comment]
Yeah this just seems like something to work through with Powershell usage. The API itself can't really do anything to handle badly encoded data. Glad you figured it out and thanks for sharing ❤️

**Comment by darrenjrobinson** [comment]
Here's my [Up Bank PowerShell Module](https://blog.darrenjrobinson.com/up-bank-powershell-module/) for anyone else interested in using PowerShell to access the Up Bank customer API.
