### ISSUE TITLE
Webhook URL limit of 120 too short for Azure Logic apps

### ISSUE THREAD

**Issue by timoconnellaus** [up-banking/api#17]
I've attempted to create a URL request endpoint in Azure Logic Apps but the URL generated is 229 characters long. When I attempt to create the webhook in the API I get an error that there is a limit of 120 characters.

![image](https://user-images.githubusercontent.com/3151605/88756290-9c94df80-d1a6-11ea-9ef6-735a55c7e820.png)

**Comment by timoconnellaus** [comment]
I think it's difficult to find an option here in Azure PaaS because you either need an auth header which doesn't seem possible or you need to put an API key in the URL which will quickly put it over 120 characters

**Comment by d11wtq** [comment]
We're going to increase the limit to 300 chars. Working on it right now, but it will require a deploy so may not be in production until tomorrow. Will let you know.

**Comment by d11wtq** [comment]
@timoconnellaus Quick update. The change has been made to allow for 300 characters and is currently making its way through our CI pipeline. It should be included in the next deploy some time tomorrow morning.

**Comment by timoconnellaus** [comment]
Thanks @d11wtq :)

**Comment by d11wtq** [comment]
@timoconnellaus this change has been deployed. Hopefully this works for you now 🤞

**Comment by d11wtq** [comment]
Closing this one off. Sing out if any further issues ❤️
