### ISSUE TITLE
Please remove the Animated GIF from your developer docs

### ISSUE THREAD

**Issue by JodieM** [up-banking/api#18]
Please.

**Comment by stewartmalik** [comment]
No, I like it.

**Comment by theg00s3** [comment]
Animated icons are kinda part of the brand identity for Up, so I doubt they'd remove it. 

Personally, I like them

**Comment by lukethacoder** [comment]
I think it actually needs more animated GIFs

**Comment by svict4** [comment]
There is an accessibility problem with the big gif though. Someone needs to slap an `aria-hidden` on it so screen readers don't read out all of that code 😅

**Comment by James-E-Adams** [comment]
Hi @JodieM. Thanks for opening an issue. Are you referring to the Up logo at the top of the sidebar, or the animated `API` logo + triangles at the top of the content? 

@svict4 Thanks for pointing that out! I've fixed it up, should be out shortly.

**Comment by levibuzolic** [comment]
@JodieM we've shipped a change that turns off some of the animations if a user has `prefers-reduced-motion: reduced` in their browser. We can extend that to remove the animated GIFs in the content too if there's demand.

**Comment by d11wtq** [comment]
How does one enable that feature in Chrome out of curiosity @levibuzolic?

**Comment by levibuzolic** [comment]
For testing purposes you can enable it in Chrome in the `Rendering` tab of the dev tools.

![image](https://user-images.githubusercontent.com/721323/89510089-7bba3300-d813-11ea-9fc8-dabafa0fc275.png)

For users it's usually an OS-level setting. On macOS it's inside the `Accessibility > Display` options in `Preferences`.

![image](https://user-images.githubusercontent.com/721323/89510186-98ef0180-d813-11ea-81d8-3bd2252b45ae.png)

On iOS it's it's `Accessibility > Motion` and Android is something like `Accessibility > Remove Animations`.

**Comment by JodieM** [comment]
Oh great, at least I can read the developer docs with the dev tools open then :/

**Comment by svict4** [comment]
@JodieM You don't need devtools to turn the animation off. If you're on windows, disable "Show animations in Windows" in the Ease of Access settings. It stops both the big animation at the top of the page, as well as the one in the menu.

**Comment by JodieM** [comment]
Oh fabulous! Thank you! (I did google for that and no such luck). I can confirm that works now.
