### ISSUE TITLE
403 Forbidden on webhook registration

### ISSUE THREAD

**Issue by ilievskizoran** [up-banking/api#2]
Keep getting `403 Forbidden` when trying to register a webhook.

Sending through Insomnia.

Method: POST
Body: 
```
{
 "data": {
   "attributes": {
    "url": "https://ed4e932a465e.au.ngrok.io/up"
   }
 }
}
```

Headers:
```
Content-Type: application/json
Authorization: Bearer up:yeah:XXXXXXXXXXXXXXXX
```

Passing in the full token, created a new one in case the current one is not working, no luck.
Using the ping endpoint works as expected.

**Comment by mtcmorris** [comment]
Ok - please give this another try now.

**Comment by ilievskizoran** [comment]
Seems to be resolved now 👍
Can you share any info on what the issue was out of curiosity?

Also would it be on your roadmap to be able to register webhooks only for specific events?

**Comment by mtcmorris** [comment]
> Can you share any info on what the issue was out of curiosity?

It was an overly enthusiastic WAF rule.

 > Also would it be on your roadmap to be able to register webhooks only for specific events?

Yeah sure.  What events specifically would you want/how would you envisage it working?

**Comment by ilievskizoran** [comment]
@mtcmorris 
Awesome, glad it was a quick fix 👍 

Some ideas:
SAVER_CREATED
SAVER_DELETED
SAVER_REACHED (as if when you reach the goal)
PAYMENT_RECEIVED (not sure you can extract somehow existing from TRANSACTION_CREATED)
PAYMENT_SENT
ROUNDUP_MADE
UPCOMING_REMINDER

Endpoint would be something like:
```
{
 "data": {
   "attributes": {
    "topic": "SAVER_REACHED"
    "url": "https://www.example.com"
   }
 }
}
```

**Comment by d11wtq** [comment]
👍 Certainly anticipate adding new events over time and agree being able to specify which events (and which accounts) you want to receive them for. Probably a little premature to add that complexity until we have sufficient numbers of event types that it becomes a problem. In terms of e.g. payment received, round up created, you would be able to infer those from the transaction data once we expose a transaction type. This is outstanding work and something we'll have (along with tags and categories).
