### ISSUE TITLE
Include failing examples

### ISSUE THREAD

**Issue by wezm** [up-banking/api#20]
The API documentation only provides happy path samples. It would be great if the "Error Response" section included samples of real error responses that might be encountered. This would make writing tests for API clients that wish to parse error responses much easier ­— since it's often not straightforward to generate and capture a real one by hand.

**Comment by d11wtq** [comment]
Yeah good call, we should definitely add those in the section about error handling. I think adding them to each endpoint would be very verbose and they all follow the same pattern, so just expanding out that error section would be 👌

**Comment by markbrown4** [comment]
Adding a sample error response to the docs, thanks!
