### ISSUE TITLE
Postman collection

### ISSUE THREAD

**Issue by arlemi** [up-banking/api#21]
Hey there! 👋  

We've seen users talking about using your OAS spec with Postman (cf [twitter](https://twitter.com/tiaan_stals/status/1287661726075248643)), and I was wondering if you were considering either:
- publishing your API to [the API Network](https://explore.postman.com/)
- creating a [Run in Postman](https://learning.postman.com/docs/publishing-your-api/run-in-postman/creating-run-button/) button for your API documentation

Let me know if you'd like me to go into more details on the differences between the two and/or how to do it. 🙂

**Comment by d11wtq** [comment]
Hi @arlemi,

Apologies for the delay in responding back here. Not missed, just need to set aside some time to look into this more closely.

**Comment by arlemi** [comment]
No worries, I understand you're still in beta and this probably isn't a priority. 😄 Please let me know here or by email (arlemi@postman.com) if you want more info.

**Comment by markbrown4** [comment]
Not planning on either for now, thanks for raising with us though!
