### ISSUE TITLE
Add transaction type to transactions response

### ISSUE THREAD

**Issue by lwithrs** [up-banking/api#22]
Hey team, absolutely loving the api being made available. Big up!

The transaction type field in the transactions csv downloadable through the UP app is super useful for categorising transactions but it's not currently available in the API response. Would love to have it available.

For reference, the below are some of the values I get in the csv export and can't see these anywhere in the api response:
Purchase
Deposit
Transfer
Osko Payment Received
Refund
Direct Credit

I also use the transaction categories in assigning my own categorisation rules but I see there's already another feature request for categories/tags.

A quick question: the description attribute of the transaction looks to match the Payee column of the csv export almost entirely, but some comparisons I've done of transactions returned from the API compared to an export from a month or so ago look to have different values. Is it the same field and the payee name has just changed since my export, or would Payee be a different field that could also be added to the api response?

**Comment by d11wtq** [comment]
Hi @lwithrs,

Transaction type is something we are working on exposing. We'll let you know when that's ready. In terms of the description field for payments, it's the exact same value used on the CSV as in the API, however that value is the name of the contact, which is a value you control through the Up application and can therefore change over time if you have edited the contact name (e.g. identified the contact).

Also be aware tags and categories are in the works in terms of being able to categorize transactions too.

**Comment by markbrown4** [comment]
The Transaction Resource will soon contain a `"transactionType"` with this value.
It'll be the same as the strings you've referenced from the CSV export.
