### ISSUE TITLE
Can't get past the 1st API request

### ISSUE THREAD

**Issue by lawyerz8** [up-banking/api#27]
I'm new to programming - trying to take baby steps to self learn. Thought Up API would be a good place to start. This is literally my first post on github, anywhere. 

I'm going a little mad as I've googled and have attempted to modify the curl query with various variations found on stackoverflow because the default example was throwing an error for me. I followed various others curl guide and also found the _same_ error so I'm quite at a lost.

It appears to be a problem with the query itself rather than an incorrect token as I don't even get to the part where I get a response. I've googled the error and the header itself and have gone through all the top 20 links on google for both without much success.

![image](https://user-images.githubusercontent.com/69147769/89175466-2d1a5800-d5cb-11ea-8434-70e3511bcbfe.png)
![image](https://user-images.githubusercontent.com/69147769/89176682-53d98e00-d5cd-11ea-87b9-93a9f2453d05.png)

I've tried:

- including/excluding the $ sign with the token
- Various formats including declaring the header separately 
- Using ' instead of " and vice versa

![image](https://user-images.githubusercontent.com/69147769/89176508-065d2100-d5cd-11ea-8db1-66e67ae28026.png)

I'm on Windows 10, using Powershell.

I know the curl function works at the very least - giving me 401 not authorised as expected without the authorisation token
![image](https://user-images.githubusercontent.com/69147769/89176118-4ff93c00-d5cc-11ea-82d3-a6258a7855af.png)

I'm hoping perhaps someone can steer me into the right direction on this. Many thanks in advance.

**Comment by d11wtq** [comment]
@lawyerz8 welcome to programming! So good to hear you're rolling up your sleeves and keen to have a go with this. I don't have a good answer for you right now (I'll try and get one... I'm less familiar with Windows). But what I can say is that you definitely don't need to (and should not) prefix a `$` sign to the token.

Imagine your token was: `up:yeah:xyz123abc` (but much longer in reality), then the correct header to send would be:

```
Authorization: Bearer up:yeah:xyz123abc
```

**Comment by d11wtq** [comment]
Try taking out that backslash before the `-H` too. The backslash is just an escaping character to handle a single curl command spanning multiple lines, but given you're supplying it all on one line, it shouldn't be needed (I imagine it will not be causing any problems, as it likely just "skips" the following space character, but remove it nevertheless).

**Comment by azz** [comment]
Hi there @lawyerz8! In Windows, `curl` is actually an alias for [`Invoke-WebRequest`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7), which has its own syntax for passing headers. You'll want to try something like this:

```ps1
$creds = 'up:yeah:...'
Invoke-WebRequest 'https://api.up.com.au/api/v1/util/ping' -Headers @{ 'Authorization' = "Bearer $creds" }
```

You can even try using `Invoke-RestMethod`, which will give you a nicer output:

```ps1
$creds = 'up:yeah:...'
Invoke-RestMethod 'https://api.up.com.au/api/v1/util/ping' -Headers @{ 'Authorization' = "Bearer $creds'  }
```

**Comment by deecewan** [comment]
also @lawyerz8  - your third screenshot was _so close_. If you want to go down the `curl` path, you can:

```powershell
$headers = @{ "Authorization" = "Bearer up:yeah:...." }
curl "https://api.up.com.au/api/v1/util/ping" -H $headers
```

But, I agree - `Invoke-RestMethod` does give a much nicer output 😄

**Comment by lawyerz8** [comment]
Thank you all! You guys are legends. Both queries above work! I'll work my way down the other examples :)

Was very confused about the " as well. Glad to note it's part of the query too now.

Interesting how Invoke-Rest method uses ' but curl/Invoke-WebRequest uses "

**Comment by deecewan** [comment]
@lawyerz8 - i might have led you astray there. It seems that in powershell, you can use either `'` or `"` - it doesn't matter. so, all of these work:

```
curl "https://api.up.com.au/api/v1/util/ping" -H @{ 'Authorization' = 'Bearer up:yeah:....' }
curl 'https://api.up.com.au/api/v1/util/ping' -H @{ "Authorization" = "Bearer up:yeah:...." }
curl 'https://api.up.com.au/api/v1/util/ping' -H @{ 'Authorization' = "Bearer up:yeah:...." }
```

which is a bit confusing - it's generally recommended to pick one kind and stick with it.

**Comment by lawyerz8** [comment]
Oh man I just discovered Postman https://www.postman.com/downloads/ isn't this so much better than CLI haha...
