### ISSUE TITLE
Webhook Ping returns an error

### ISSUE THREAD

**Issue by ethene** [up-banking/api#29]
When calling Ping url via Curl (as per example)

`curl https://api.up.com.au/api/v1/webhooks/316c2282-4b75-4539-9561-1893564d4dad/ping \
>   -XPOST \
>   -H 'Authorization: Bearer up:yeah ...`

it returns with an error like:

`<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 411 (Length Required)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>`

**Comment by d11wtq** [comment]
@ethene is this response coming from the Up API directly in response to the ping request? Or is this coming from your webhook URL in response to the event we send to it? This particular request in the API does not have any content in the body. Does it work if you include `-H 'Content-Length: 0` in the command? Will update the documentation if it's an issue with the example request in the docs.

Thanks for reporting.

**Comment by d11wtq** [comment]
You could also try `--data-binary ''` which likely triggers the same header to be automatically added.

**Comment by d11wtq** [comment]
Have reproduced this. It wasn't happening for me as my version of `curl` has `HTTP/2` support, so was using that, which apparently works. Forcing `HTTP/1.1` you will get this error without a content length. Passing `--data-binary ''` or `-d ''` will give the correct result. We'll update our docs ❤️

**Comment by d11wtq** [comment]
@ethene we've made a change to our documentation to address this (essentially pass an explicit empty string for the body). Thanks for reporting!
