### ISSUE TITLE
How do I see Categories or Tags for transactions? 

### ISSUE THREAD

**Issue by scottgbailey** [up-banking/api#3]
Hi,

I'm really keen to be able to see a spending breakdown over the year by Categories or Tags. Anyway to see the tags I've allocated to my transactions?

**Comment by d11wtq** [comment]
Hi @scottgbailey,

Thanks for reaching out. We'll get to it, but currently that is not implemented in the API. Not a design choice, just not yet implemented. Watch this space.

:heart:

**Comment by d11wtq** [comment]
Will leave this open as a feature request.

**Comment by d11wtq** [comment]
Quick update @scottgbailey and everybody else, the ability to see which tags are associated with a transaction shipped earlier today, along with the ability to add/remove tags to transactions. Currently flowing through the pipes of our CI infrastructure is the ability to list all tags and to filter transactions by tag. Most likely that second change won't ship to production until tomorrow morning now.

Categories is next on the list...

**Comment by d11wtq** [comment]
Quick update. Listing tags and filtering by tags has now shipped. This means you can now:

  - [x] See which tags are associated with a transaction
  - [x] See all tags you're using
  - [x] Add tags to a transaction
  - [x] Remove tags from a transaction
  - [x] Filter the transaction list to a given tag

Will let you know when categories is ready.

**Comment by d11wtq** [comment]
Quick update. Categories are now returned on the transaction resource. You can get a full list from `/api/v1/categories`. Filtering and updating are not yet implemented but should follow.

**Comment by hen-zone** [comment]
@d11wtq I'm not seeing `/api/v1/categories` in the OpenAPI blob — is that just awaiting an export?

**Comment by d11wtq** [comment]
Responded on the other issue regarding incorrect description on tags. Same reason: pending an export from upstream. Will get an update into this repo shortly 😎

**Comment by d11wtq** [comment]
Both categories and tags are in production as of last week. Will close this one off.

**Comment by martintburgess** [comment]
Just a note to say thank you! Loving this API and the responsiveness of the team.
