### ISSUE TITLE
Scan the (non existent?) QR Code to get your Personal Access Token

### ISSUE THREAD

**Issue by DC7T3xer** [up-banking/api#30]
https://api.up.com.au/getting_started is not showing a QR code, only an animated Up logo. Is this an intentional thing to limit the beta, or a problem with the getting started page? Could this also be the beginning of a quest to include more [animated gifs?](https://github.com/up-banking/api/issues/18#issuecomment-667521307)

![image](https://user-images.githubusercontent.com/12839614/89476581-6a026c80-d7ce-11ea-9552-70cfa20278ca.png)

**Comment by d11wtq** [comment]
Investigating. Can you see any errors in the JavaScript console in your browser @DC7T3xer? Which browser are you using?

**Comment by DC7T3xer** [comment]
![image](https://user-images.githubusercontent.com/12839614/89480657-41cc3b00-d7d9-11ea-87d2-937ae6952fe9.png)

**Comment by d11wtq** [comment]
Thanks. Investigating. Certainly not an expected situation. You should be getting a QR code rendered there once the page has loaded.

**Comment by DC7T3xer** [comment]
@d11wtq Could be a firewall thing, the QR code is visible on my mobile but not my work machine, try not to smash yourself figuring this one out.

**Comment by d11wtq** [comment]
I was literally about to ask if you're behind a corporate firewall that may be blocking/breaking the websocket 👍

**Comment by DC7T3xer** [comment]
I'm happy to employ a workaround as this obviously won't happen for everyone. If you're happy with that, then this issue can be closed.

**Comment by d11wtq** [comment]
:+1: I'll close this for now, but do chime back in if you find it has nothing to do with the firewall.
