### ISSUE TITLE
"Remove tags from transaction" - Incorrect documentation description 

### ISSUE THREAD

**Issue by aaronvanston** [up-banking/api#32]
Hi team!

Love working with the new API, keep up the amazing job!

I've noticed the description for `Remove tags from transaction` is incorrect and seems to be a copy + paste from the removing webhook section

https://developer.up.com.au/#delete_transactions_transactionId_relationships_tags

> Delete a specific webhook by providing its unique identifier. Once deleted, webhook events will no longer be sent to the configured URL.

As seen here https://github.com/up-banking/api/blob/master/v1/openapi.json#L1508

**Comment by d11wtq** [comment]
Whoops! Copy/paste indeed. Thanks for the heads-up. Will get a fix out today 🙉

**Comment by d11wtq** [comment]
All fixed!
