### ISSUE TITLE
Feature request: Expose opaque cursors for each paginated result

### ISSUE THREAD

**Issue by aaronvanston** [up-banking/api#34]
Hi team!

Just a thought and feature request I had. 

For any paginated resource, it would be great to know the opaque cursor for each item so we have specific control over how pagination works. This way we can choose any "edge" within a resource connection and start the page after/before that. 

Right now for custom pagination logic, I'm having to perform regular expression/ split the links provided to attach additional params (custom page size etc). This can only be done on the start and end elements.

**Comment by d11wtq** [comment]
@aaronvanston can you share your use case? Specifically because we don't want to be bound by any particular pagination strategy, we require that you use the links to get the next and previous pages. What's the use case for not following the links? Filter parameters etc should be retained through those links.

**Comment by d11wtq** [comment]
Custom page size should also be retained through those links too. Is that not working?

Essentially:

```
GET /api/v1/transactions?page[size]=2&filter[tag]=Pizza
```

Each `next` and `prev` link should get you the next/prev 2 records for transactions tagged Pizza. There's no need to copy the filter parameters manually and any other parameters you might be passing would be doing nothing anyway (as we only retain the parameters that are actually used).

**Comment by aaronvanston** [comment]
@d11wtq Yes, these are working fine 😄 

To be specific on the use case I wanted to implement [relay style pagination ](https://relay.dev/graphql/connections.htm) which requires a cursor for each time. I understand that it would be moving towards this particular type of pagination so that makes sense 😛 

For me having a cursor for each gives more flexibility to start paginating on any element. Aside from wanting to implement this spec over standard cursor pagination, there is no strong use case.

**Comment by d11wtq** [comment]
:+1: Worth noting that from that specification, the presence of a cursor on every record is largely historical:

> As this spec was created with Relay Classic in mind, it’s worth noting that Relay Legacy did not define startCursor and endCursor, and relied on selecting the cursor of each edge; Relay Modern began selecting startCursor and endCursor instead to save bandwidth (since it doesn’t use any cursors in between).

Relay these days just refers to the `pageInfo` to get a `startCursor` and `endCursor`. I'm still not sure what the practical use case would be for splitting a page in two and paginating from an arbitrary point within it, vs just supplying a different page size to begin with.

Understand the flexibility. I just can't see a real-world use case it solves, weighed against the downsides of exposing the underlying pagination strategy in the API and going against the use of HATEOAS to drive the navigation within the API.

**Comment by aaronvanston** [comment]
Thanks @d11wtq for summarising! Yeah all good, understanding that without a strong use-case it's just adding bloat! Happy to close this and implement it without a cursor on each edge. Cheers!
