### ISSUE TITLE
Acceptable use policy inaccessible after closing auth_granted page

### ISSUE THREAD

**Issue by epetousis** [up-banking/api#4]
Minor issue, but I generated a new auth token on api.up.com.au and opened the 'acceptable use policy' link in another tab. This landed me on an error page, but I didn't actually notice until I closed the original auth_granted page. Is the policy accessible after the fact or do I need to reauthorise?

**Comment by d11wtq** [comment]
Hi @epetousis,

Thanks for the heads-up. We seem to have any issue with that link not going anywhere useful. We'll take it out briefly and put it back in with a fix ASAP.

**Comment by d11wtq** [comment]
This was fixed a couple of days ago.
