### ISSUE TITLE
Incorrect description for `tags/delete`

### ISSUE THREAD

**Issue by hen-zone** [up-banking/api#41]
Hi there! I'm loving this API documentation.

It looks like there is an error on the `description` field for the `delete` method on `/transactions/{transactionId}/relationships/tags`. The text of the description refers to webhooks, rather than tags. Possibly this was accidentally copied from another field.

The line in question is here: https://github.com/up-banking/api/blob/master/v1/openapi.json#L1508

**Comment by d11wtq** [comment]
Hi @hen-zone apologies; this has been fixed upstream but the OAS hasn't been exported back to this repository. I will sort this out this morning. We should probably automate this!

**Comment by d11wtq** [comment]
Just pushed up the updated OAS blob now. Sorry about that 😅
