### ISSUE TITLE
Account Reconciliation Variance 

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#43]
Hi Team, I have been having a lot of fun with the API and with the assistance of other Upsider via this [repo](https://github.com/legionsystems/upbanking) I've been able to dump all transactions into excel using power query.

However, when reconciling the accounts summary totals, vs the transactions totals, there is a variances. I can see when I check some transfers, they result in a negative balance or an 1.E15 error in excel.

My variance seems to be consistent at $4.11 and I've been monitoring it as I make more purchases/transfers as I use my account.

I would be happy to share my document with devs to debug if needed.

Thanks!

**Comment by d11wtq** [comment]
Hi @gxander85 let me look into this for you 🤔 

Would you mind sending a message via Talk to Us in the app, with a link to this Github issue, so I can get your account details confidentially and try and work out what's going on.

**Comment by gxander85** [comment]
Done! I can also share my files via a Dropbox share link via the app chat too if needed.

**Comment by d11wtq** [comment]
💬 Handling this via Talk to Us in app, so will close this off.
