### ISSUE TITLE
Tagged Transactions

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#44]
Is there a way to have the tags for transactions to appear as a comma separated value rather than a list then records for each?
Multiple Tags generate multiple lines for the same transactions.
I've done a manual work around via PowerQuery & Excel, but it's messy 😬

**Comment by d11wtq** [comment]
Can you clarify what you mean? I'm not clear on this:

> Multiple Tags generate multiple lines for the same transactions.

We wouldn't be able to comma-separate, as comma is an allowable character in tags.

**Comment by gxander85** [comment]
Sure, here is an example.

Tags are set as a list that contains a record for each tag that is present.

Here is one tag on a transaction
![image](https://user-images.githubusercontent.com/19649506/90863903-1d747f00-e3d3-11ea-89e5-ec78ecf99490.png)
As you can see, the list contains one record.

Here is two tags
![image](https://user-images.githubusercontent.com/19649506/90863872-12215380-e3d3-11ea-860b-4c2ff9fd2571.png)
This list contains two records.

When you expand the list and then the records, it creates a new row for each 'tag'
![image](https://user-images.githubusercontent.com/19649506/90863972-37ae5d00-e3d3-11ea-82f8-41aacd877905.png)

So when you look at totals, summarise or pivot the data, it's inaccurate. (This is not the reason behind the issue I posted earlier)

Ideally it would be great to have the initial tags under relationships to be a record and not a list.
The record would contain one value for each tag.
Then you can expand the record column to
"tags", {"tags.tag1","tags.tag2","tags.tag3"}
I believe it's max of 6?

This would create one column for each tag, I can then concatenate within PowerBi or Excel.

**Comment by d11wtq** [comment]
🙇
