### ISSUE TITLE
Seperate Saver Emoji & Name from `displayName` field

### ISSUE THREAD

**Issue by jakehwll** [up-banking/api#45]
Hey guys

Was curious if you could seperate these two into their own keys rather than concatenating them to one?

Would rather not have to work some regex magic to make this emoji bigger.. Legends!

https://upbank.netlify.app/

![image](https://user-images.githubusercontent.com/49461152/90955474-09a74680-e4c1-11ea-9f59-8b57582b2d7a.png)

**Comment by markbrown4** [comment]
Combining this request with https://github.com/up-banking/api/issues/10
