### ISSUE TITLE
PHP example in docs has issues

### ISSUE THREAD

**Issue by aliask** [up-banking/api#49]
Noticed a couple of issues while implementing in Laravel.

1. Using `php://input` is problematic for tests, and generally fails in older versions of PHP.
2. If header is missing, hash_equals will throw an exception - better to use `?? ''` to ensure variable is non-null.
3. Trailing , in header() call

Revised code to address these issues:
```php
public function handleWebhookEvent(Request $request, $hook) {
    $received_signature = $request->header(
        'X-Up-Authenticity-Signature'
    ) ?? '';
    $raw_body = $request->getContent();
    $signature = hash_hmac('sha256', $raw_body, $hook->secret_key);
    if (!hash_equals($signature, $received_signature)) {
        abort(401);
    }
    // Process webhook event
}
```

**Comment by d11wtq** [comment]
Fix incoming 🚢
