### ISSUE TITLE
Unable to paginate Accounts endpoint

### ISSUE THREAD

**Issue by scottgbailey** [up-banking/api#5]
Hi,
Try get to get page 4 by doing the following: 
Get links from : https://api.up.com.au/api/v1/accounts?page[size]=3 
use the links "next" but I'm receiving Status 500 Internal Server Error.

works okay with : accounts/?AccountsID?/transactions?page%5Bafter%5D

**Comment by d11wtq** [comment]
Thanks for reporting this @scottgbailey. Sorry to see you're hitting this. Have tracked this down and will need to get a code change and a deploy out to resolve it. Unfortunately it probably won't be in production until tomorrow, but will let you know once ready.

**Comment by staticfrost** [comment]
All good thats what beats are for :D

**Comment by scottgbailey** [comment]
No worries, that's why we all do betas :D, thanks for looking at it so quickly!

**Comment by d11wtq** [comment]
@scottgbailey would you mind giving it another go? Hopefully it should be working ok now 🤞

**Comment by scottgbailey** [comment]
@d11wtq , that's working really well now thanks 👍

**Comment by d11wtq** [comment]
🎉 Fantastic, glad it's sorted. Thanks for confirming.
