### ISSUE TITLE
Attributes Missing

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#51]
Hi, I have discovered an issue with calling on the API and only pulling the most recent batch of transactions. If an attribute has not been used, it does not exist in that specific call.

Example. Boost Round Ups are switched off within app. `attributes.roundUp.boostPortion.currencyCode, attributes.roundUp.boostPortion.value, attributes.roundUp.boostPortion.valueInBaseUnits` are all missing.
This is not limited to just boostPortion. Any attribute that is not present in the call is not within the JSON strings.

This causes issues with matching columns to a full history. I am reworking a flow in Parabola and pulling in the full history from a Google Sheet and matching to updated transactions from a single 100page call. If the columns don't exist, I cannot match them up.

Can all attributes be present even if null? The result would just be blank, but column header would be present.

**Comment by d11wtq** [comment]
Hi @gxander85, the `roundUp` field itself is documented as nullable. What kind of object would we put in the field if there was no round-up? Similarly, the `boostPortion` on a round up is nullable, because if there's no boost what would we put there? I'm not clear what you're proposing would go in the fields in the case there's no round up.

At some point, you either have to choose not to return the field, or make it nullable. Not everything can have a value if there's no value associated with it.

Can you give a direct example of a payload and what you would want to change it to?

**Comment by d11wtq** [comment]
I think with these kinds of issues where the payload does not map 1:1 with the software, you will probably need to transform the data structure before loading it in. I don't think I'd be a huge fan of something like:

```
"roundUp": {
  "amount": {
    "currencyCode": null,
    "value": null,
    "valueInBaseUnits": null
  },
  "boostPortion": {
    "currencyCode": null,
    "value": null,
    "valueInBaseUnits": null
  }
}
```

Now to work out if a transaction had a round up you need to deeply traverse the amount structure for a round up that never happened. It also means we'd have to document the `MoneyObject` type as having nullable fields everywhere (and presumably every object type's fields).

**Comment by gxander85** [comment]
Hi, sorry I will be a bit more clear. When the most recent 100 lines are called from the API, if an attribute is not used, it is not expanded and is shown as the example below.
```
"roundUp": null,
```
Rather than

```
"roundUp": ,{
  "amount": {
    "currencyCode": null,
    "value": null,
    "valueInBaseUnits": null
  },
  "boostPortion": {
    "currencyCode": null,
    "value": null,
    "valueInBaseUnits": null
  }
}
```
I would have expected all attributes to fully expand when null is returned.

**Comment by d11wtq** [comment]
The best I can suggest is that you first normalize the data structure to place the nulls where you would like them, so e.g.

```
if (attributes.roundUp == null) {
  attributes.roundUp = {
    amount: {
      currencyCode: null,
      value: null,
      valueInBaseUnits: null
    },
    boostPortion: null
  };
}

if (attributes.roundUp.boostPortion == null) {
  attributes.roundUp.boostPortion = {
    currencyCode: null,
    value: null,
    valueInBaseUnits: null
  };
}
```

But it seems like potentially there's a better approach to solving this problem, by extracting the data you need from the response into a structure that makes sense for your use case, and then passing that extracted data into whatever your process is for handling the data.

**Comment by gxander85** [comment]
Sadly there is no simple way to achieve this in Parabola.
What I did do, is create an attributes list within Google Sheets.
Expand the API Call out, flip the table, merge it with the attributes list, then flip it back.

This seems to have worked for now.

This of course only works if the attribute names remain as is. I am sure they will.

I will look into a way to try achieve the above, but not sure I can in the program I am using. Thanks again!

**Comment by d11wtq** [comment]
That solution sounds like a good one to me, yeah 👍 Glad to heat you figured out a way.
