### ISSUE TITLE
Certain emojis missing from displayName

### ISSUE THREAD

**Issue by joshmeney** [up-banking/api#57]
Just noticed that when fetching a either a list of all accounts or a single account, if certain emojis are used for the Saver, then the displayName is returned with no emoji included.

Haven't tested exhaustively so don't know how widespread this is but after choosing 10 emojis at random, found that both 🤖 (robot) and 🧑‍🔧 (mechanic) don't work,

**Comment by d11wtq** [comment]
Thanks for the heads up @joshmeney. We store the emoji name itself and are using a library to get the actual emoji. On the app this is handled by the client side in both directions, so there's probably a gap between the two solutions, or simply we need to add some aliases. Will look into the ones you mentioned. Any others let us know and we can have a look too.

When we expose more detailed Saver info we'll likely expose the emoji name in addition to its Unicode character in a more structured fashion than we're doing here.

**Comment by d11wtq** [comment]
We've defined a mapping that means this should now be fixed 🙇
