### ISSUE TITLE
URL scheme on iOS

### ISSUE THREAD

**Issue by iJas0n** [up-banking/api#59]
I was wondering if it’s possible to open the details page of a particular transaction in the iOS app by using the API to extract the transaction id for the transaction.

I’ve noticed that up:// opens the Up app, and that up://transactions/[transaction id] opens the Up app but errors with the “Transaction Not Found” page. Clearly, there must be some scheme to open a particular transaction, perhaps by transaction id. Can someone shed some light here?

![3D3DD627-E0FE-461A-8DB1-8C14B23C1C78](https://user-images.githubusercontent.com/4646520/92986313-f48c6900-f4fc-11ea-88d6-82c40c2dd27f.png)

**Comment by d11wtq** [comment]
Good idea @iJas0n. Have raised for discussion internally ❤️ We'd have to release an app update to support this, as as you've noted the IDs in the API will not currently work with the app out of the box.

**Comment by iJas0n** [comment]
@d11wtq Thanks for your time and consideration!

**Comment by markbrown4** [comment]
Transactions will soon contain a "deepLinkURL" with this value. e.g. "up://transaction/:id"
When followed on a mobile device with Up installed, it'll load the transaction receipt.

**Comment by markbrown4** [comment]
Apologies, this field has been temporarily removed.

**Comment by markbrown4** [comment]
`deepLinkURL` has been returned.

https://developer.up.com.au/#transactions
