### ISSUE TITLE
Handle URL encoded square brackets in query params

### ISSUE THREAD

**Issue by nick96** [up-banking/api#61]
Square brackets in URLs are non-standard so some HTTP client libraries don't play nice with them. Is it possible for the API to understand URL encoded square brackets (e.g. `page%5Bsize%5D%3D1` in addition to `page[size]=1`)?

**Comment by d11wtq** [comment]
@nick96 It does understand URL-encoded square brackets. Are you having a problem with a specific call?

**Comment by d11wtq** [comment]
In particular if you look at the `links` in a paginated response you'll see we URL encode these characters ourselves and those URLs definitely work as expected.

**Comment by nick96** [comment]
Thanks for the quick response! Okay, I must be going wrong somewhere else. I'll dig into it this evening. The specific problem that I'm having is that my transaction requests aren't being paginated to the page size I'm specifying.

**Comment by nick96** [comment]
Just had a quick look and I'd messed up and made a typo. Sorry for jumping the gun

**Comment by d11wtq** [comment]
TBH we can probably get better at rejecting unhandled query parameters (e.g. returning a 400, or putting some message in the metadata).
