### ISSUE TITLE
Be able to add tags for payments (one off and scheduled) before the transactions is complete

### ISSUE THREAD

**Issue by gregless22** [up-banking/api#63]
At the moment you can only add a tag after a payment has been processed (via the app or the API). Would be good if you could add a tag while doing a payment or setting up a scheduled payment.  That way it would be very easy to filter automated transactions via the API.  

For example I set up a reoccurring transaction to pay off a loan.  I would like to tag it with 'Loan" so I can filter via the API and easily see how much I've paid.  Currently I need to go through each scheduled transaction after it has been completed and tag it.

**Comment by d11wtq** [comment]
Agree this would be super useful to have in the Up app.

**Comment by legionsystems** [comment]
Not sure if you are still following this - but when I last did a Scheduled Payment - I was able to make this change for upcoming payments.

**Comment by markbrown4** [comment]
Yep, you can add categories to scheduled payments in-app now.
You can also now update categories and tags via the API.
