### ISSUE TITLE
Add from/to account ID for transfer transactions

### ISSUE THREAD

**Issue by daveallie** [up-banking/api#66]
Currently, transfers look like regular transactions, with the description attribute containing: "Transfer to x" / "Transfer from x".

While there is a relationship the account where the transaction was made, there's no surefire way to programmatically determine the account ID of the account where the money came from / went to. Easiest way I assume would be to check the description with a string match and then find the account with the same name.

I'd love for an additional relationship to the from/to account or have some other way to programmatically determine the account ID without having to look up accounts.

Maybe something like:

```js
{
    "data": {
        "type": "transactions",
        "id": "xxx",
        "attributes": {
            // ...
        },
        "relationships": {
            "account": {
                "data": {
                    "type": "accounts",
                    "id": "yyy"
                },
                "links": {
                    "related": "https://api.up.com.au/api/v1/accounts/yyy"
                }
            },
            "transferAccount": {
                "data": {
                    "type": "accounts",
                    "id": "zzz"
                },
                "links": {
                    "related": "https://api.up.com.au/api/v1/accounts/zzz"
                }
            },
            // ...
        },
        "links": {
            "self": "https://api.up.com.au/api/v1/transactions/xxx"
        }
    }
}
```

**Comment by d11wtq** [comment]
Agree we absolutely should have this ❤️

**Comment by d11wtq** [comment]
This has been implemented, exactly as the example shows in the original issue description. It should be deployed some time today ❤️

**Comment by daveallie** [comment]
Works perfectly, thanks!
