### ISSUE TITLE
De-register Access Token in app

### ISSUE THREAD

**Issue by yogeshpathade** [up-banking/api#7]
I think the Documentation needs to add some details on the Access Token Session Validity.

**Comment by d11wtq** [comment]
So currently we're in beta and the API is open for personal use only (no sharing your token with a third party). In this phase there is no automatic expiry of the access token. You can revoke it by issuing a new token (which replaces the current one). Once we start supporting third parties accessing your data through the API we will indeed have token expiries and scopes etc and will document those accordingly.

**Comment by yogeshpathade** [comment]
@d11wtq It will be cool to revoke the token from the App Security Settings

**Comment by d11wtq** [comment]
Absolutely, that's on the list 👍

**Comment by drnic** [comment]
You revoke your token by creating a new token. It looks to only support one token at a time.

**Comment by markbrown4** [comment]
Thanks for raising @yogeshpathade!
I agree, we should show allow access tokens to be removed in app.

**Comment by markbrown4** [comment]
You'll be able to revoke your tokens under Up > Data Sharing in the next release.
