### ISSUE TITLE
Add bank details for transactions

### ISSUE THREAD

**Issue by pacobalt** [up-banking/api#70]
Hi, are there plans to add bank details for incoming and outgoing transactions?

**Comment by d11wtq** [comment]
Do you mean on the accounts or on the transactions themselves? We are unable to show The payer's BSB/Account for regulatory reasons on Osko/NPP, but we certainly plan to add more structure generally around incoming/outgoing payments, much like in the Up app.

**Comment by pacobalt** [comment]
I did mean the bank details of the payer on the transactions. 
Alright, that sounds great. I am looking forward to it.
