### ISSUE TITLE
Incorrect Data returned when using filter rent-and-mortgage

### ISSUE THREAD

**Issue by legionsystems** [up-banking/api#71]
I have several transactions categorized as rent-and-mortgage however the filter isn't returning them correctly.

![image](https://user-images.githubusercontent.com/56010379/101607696-fc569d80-3a58-11eb-927c-7b018eba00c9.png)

Other Categories I've tried have filtered correctly.

**Comment by legionsystems** [comment]
Ok - further working on this - it seems to be if you do a transfer to another persons bank (real estate in this instance) it isn't included in this category.
I had a similar issue with family category also not showing up when doing the same thing.

**Comment by d11wtq** [comment]
Thanks for reporting this @legionsystems. Will dig into it and get back to you.

**Comment by lutzenburg** [comment]
Forwarded transactions also seem to lose this information. So payments to  me that I have tagged as "rent-and-mortgage" and forwarded to my rent saver aren't able to be filtered by the API.

**Comment by d11wtq** [comment]
I notice in this screenshot that `filter[since]` and `filter[until]` are backwards. This request translates as `createdAt >= '2020-09-01' AND createdAt <= '2020-01-30'`, which is logically impossible. Is this still an issue?

**Comment by lutzenburg** [comment]
Just had another look. Removing the time filters, I have the same result. 

![image](https://user-images.githubusercontent.com/11610578/150360960-4b48d6b7-30a4-4454-a543-e9af02280a23.png)

I have transactions with this category from within the last couple of weeks. Using a different category such as `life-admin` gives me the expected result (all the transactions I know to be categorised by `life-admin`).

**Comment by d11wtq** [comment]
I just had a look at this myself and it worked for me, but there are various ways categories can be assigned, so keen to get more insight. In my case I just manually categorised an existing transaction as "Rent & Mortgage" via the app, then queried for transactions using that category via the API. The transaction was correctly returned. Is the transaction you're expecting to see manually categorised, or was it categorised automatically by Up?

I'm also seeing a `%20` (space) in that URL in the screenshot following the path and before the query string, though I don't think it'll be related.

**Comment by d11wtq** [comment]
Oh I think I've found it! The transaction I categorised was a card purchase. I just did the same with a payment and it's not coming through like you say. Digging deeper :eyes:

**Comment by d11wtq** [comment]
Ok, this issue seems broader than the category selection itself. It looks like payments aren't being picked up by the filter but other transaction types are. I think I've found the source of the problem too. Will make sure it's covered by a suitable test and get a fix out.

**Comment by d11wtq** [comment]
We have implemented a fix for this that should go out shortly.

**Comment by legionsystems** [comment]
I'm glad this is fixed - and thank you for addressing it :)
I think it had to do with anything that was a transfer - not an actual transaction (like a tap & pay etc)

**Comment by d11wtq** [comment]
Thanks for reporting it! The fix for this has now been deployed 🚀
