### ISSUE TITLE
Cannot find module npm error

### ISSUE THREAD

**Issue by hamish-klemp** [up-banking/api#73]
Hi There,

I am following the YouTube tutorial on the UP API, and am up to Ep. 7, however am unable to run the npm start. I get the "Error: Cannot find module 'D:\nodemon\bin\nodemon.js'".  Googling tells me I need to do complicated things like re-assigning the path in control panel, but none of this was need for Jon in the tutorial. Can someone please assist where I am going wrong. Have uninstalled and re-installed from scratch but getting same issue.

Thanks

Hamish

**Comment by Hona** [comment]
@hamish-klemp this has nothing to do with the Up Banking API, you might want to learn more about JS and NPM instead. You mentioned a tutorial video but didn't include the link?
