### ISSUE TITLE
Ability to alter/add categories to transactions 

### ISSUE THREAD

**Issue by johnny-liaw** [up-banking/api#74]
Hi up team! 

Currently there is the ability to alter and add tags via the endpoint, is there plans to add functionality where we can alter and change the category of transactions in the future and when this would be available? Thanks!

**Comment by d11wtq** [comment]
Yeah we should absolutely do this :+1:

**Comment by d11wtq** [comment]
I guess it would be implemented to match tags, except to-one and not to-many:

```
POST /transactions/{id}/relationships/category

{
  "data": {
    "type": "categories",
    "id": "hobbies"
  }
}
```

**Comment by dannyZyg** [comment]
I would also love this feature! Just started messing around with the API and was hoping this would be in there! :shopping_cart:

**Comment by d11wtq** [comment]
This got auto-closed as I merged a PR to add this functionality. It should be available in production later today or early tomorrow 🙇

**Comment by d11wtq** [comment]
This is now released: https://developer.up.com.au/#patch_transactions_transactionId_relationships_category

**Comment by dannyZyg** [comment]
This should be very useful, thanks so much for implementing!
