### ISSUE TITLE
POST Tag Help

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#79]
Hi Folks, less an issue but more a request for help.
Can anyone help out a novice with some instructions or guideance in how to POST tags to transactions? I have a list of Transaction IDs and Tags I wish to add, but I have no idea where to start. What software to use? How to set it up? Any assistance would be greatly apprecited! Thanks!

**Comment by johnmee** [comment]
Did you try it with `curl` as described in the example in the documentation?

https://developer.up.com.au/#post_transactions_transactionId_relationships_tags

**Comment by gxander85** [comment]
Hi, I could I just don't know how, hence the request for help.

My only experience with API has been with GET. I've never needed to POST.

**Comment by d11wtq** [comment]
curl on the command line is useful when you're looking to explore the API or in shell scripting, but if you're actually writing software to handle this I'd use whatever HTTP client is most commonly used for the language you're working in.

For example, something like Axios in NodeJS, RestClient or Faraday in Ruby, or indeed the curl wrappers in PHP. Do you know what programming language you'll be using?

**Comment by d11wtq** [comment]
Here's an example using axios in NodeJS.

``` javascript
const axios = require('axios');

async function addTagsToTransaction(transactionId, tagNames) {
  const response = await axios.post(
    `https://api.up.com.au/api/v1/transactions/${transactionId}/relationships/tags`,
    JSON.stringify({
      data: tagNames.map(t => ({type: 'tags', id: t})),
    }),
    headers: {
      'Content-Type': 'application/json',
      `Authorization: Bearer ${token}`,
    },
  );

  if (response.status != 204) {
    throw new Error('unexpected response');
  }
}
```

**Comment by gxander85** [comment]
Hi, I will level with you here. I'm not very good at programming. My experience currently is via a query someone else wrote that I've used to Get the transactional data into excel.

I'm searching for a tool that already exists that needs some basic config and setup that I can use. Like postman or something.

I don't see this as an ongoing thing so it can be a manual process if needed.

Just keen to bulk update tags I've missed and got lazy with not updating.

**Comment by VeryStrongFingers** [comment]
@gxander85 if you're after a code-free solution, as you said there's always Postman - but if you want a more focused API experience try out https://insomnia.rest/
using a scripting/programming language would only be practical for you if you're wanting to automate something.

I created a sample workspace for Insomnia to show you some API interactions
Save this JSON as "workspace.json"
```json
{"_type":"export","__export_format":4,"__export_date":"2021-03-29T01:29:25.275Z","__export_source":"insomnia.desktop.app:v2020.5.1","resources":[{"_id":"req_924e39af72b14cc689d726256eacb613","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981342748,"created":1616981093501,"url":"https://api.up.com.au/api/v1/transactions/{% prompt 'Transaction ID', '', '11e812cf-a2fc-4c18-b9a1-6922103cd9eb', '', false, true %}/relationships/tags","name":"Add tags to transaction","description":"","method":"POST","body":{"mimeType":"application/json","text":"{\n\t\"data\": [\n\t\t{\n\t\t\t\"type\": \"tags\",\n\t\t\t\"id\": \"Holiday\"\n\t\t}\n\t]\n}"},"parameters":[],"headers":[{"name":"","value":"","description":"","id":"pair_6237d01c8498450ea92fd819858cd2f8"},{"name":"Content-Type","value":"application/json","id":"pair_1356e2ac45ae4112a02352a6f96f6c68"}],"authentication":{"type":"bearer","prefix":"Bearer","token":"up:yeah:token"},"metaSortKey":-1616981093502,"isPrivate":false,"settingStoreCookies":true,"settingSendCookies":true,"settingDisableRenderRequestBody":false,"settingEncodeUrl":true,"settingRebuildPath":true,"settingFollowRedirects":"global","_type":"request"},{"_id":"wrk_d640746ebba1437bbe256eb3c38c5394","parentId":null,"modified":1616981070957,"created":1616981070957,"name":"Up API","description":"","scope":null,"_type":"workspace"},{"_id":"req_c4fe59db41e5420c85a7a77e3a569643","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981338413,"created":1616981219187,"url":"https://api.up.com.au/api/v1/accounts","name":"List accounts","description":"","method":"GET","body":{},"parameters":[],"headers":[{"name":"","value":"","description":"","id":"pair_6237d01c8498450ea92fd819858cd2f8"}],"authentication":{"type":"bearer","prefix":"Bearer","token":"up:yeah:token"},"metaSortKey":-1616527914991,"isPrivate":false,"settingStoreCookies":true,"settingSendCookies":true,"settingDisableRenderRequestBody":false,"settingEncodeUrl":true,"settingRebuildPath":true,"settingFollowRedirects":"global","_type":"request"},{"_id":"req_43a43c5186df4a5d83b0a4de9fa6bca0","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981340579,"created":1616981258963,"url":"https://api.up.com.au/api/v1/transactions","name":"List transactions","description":"","method":"GET","body":{},"parameters":[],"headers":[{"name":"","value":"","description":"","id":"pair_6237d01c8498450ea92fd819858cd2f8"}],"authentication":{"type":"bearer","prefix":"Bearer","token":"up:yeah:token"},"metaSortKey":-1616301325735.5,"isPrivate":false,"settingStoreCookies":true,"settingSendCookies":true,"settingDisableRenderRequestBody":false,"settingEncodeUrl":true,"settingRebuildPath":true,"settingFollowRedirects":"global","_type":"request"},{"_id":"env_25e0ad009e0f35ca47a873a25f4969c83c93fc70","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981071150,"created":1616981071150,"name":"Base Environment","data":{},"dataPropertyOrder":null,"color":null,"isPrivate":false,"metaSortKey":1616981071150,"_type":"environment"},{"_id":"jar_25e0ad009e0f35ca47a873a25f4969c83c93fc70","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981071151,"created":1616981071151,"name":"Default Jar","cookies":[],"_type":"cookie_jar"},{"_id":"spc_339ceb1858c94cd8b89faa17c4fe4ec1","parentId":"wrk_d640746ebba1437bbe256eb3c38c5394","modified":1616981070985,"created":1616981070985,"fileName":"Up API","contents":"","contentType":"yaml","_type":"api_spec"}]}
```
and import it as a workspace in your Insomnia client, make sure to put your own Authentication token from Up in the Auth/Bearer tab

**Comment by gxander85** [comment]
@VeryStrongFingers Hi, definitely looking for as code free as possible. I've never used Postman, but I started to play around with it over the weekend. I would appreciate if anyone has any guidance on how to use it to post tags.

**Comment by d11wtq** [comment]
I just had a look at insomnia, which @VeryStrongFingers posted above and imported that JSON blob. It looks like that will do what you need. It basically lets you specify a bunch of tags (in the correct JSON format) and prompts you for the transaction ID (from the API) to apply those tags to. I imagine it would translate well to Postman too, if you essentially copy the request details into Postman, but I'm not familiar with either tool. These are UI-driven tools though so probably just try and see where you get stuck.

**Comment by gxander85** [comment]
Hey folks, I have been able to get support from the Postman team. Posting here if others wish to use the same service.
https://community.postman.com/t/post-guidance-for-a-newbie/22017/3
This can now be closed
