### ISSUE TITLE
API Ratelimits

### ISSUE THREAD

**Issue by CyberiumShadow** [up-banking/api#8]
Hey,

So I don't seem to see any section in the documentation regarding Rate-limits (global nor per-endpoint)

As far as I can see, the only way to see what our rate-limit is via the `X-RateLimit-Remaining` header that is returned in the response from the API.
From what I understand, this rate-limit should be hourly but I feel that it would make it easier/more understandable to other people working with the API to have the rate-limits documented.

**Comment by d11wtq** [comment]
You are correct; that is an hourly rate limit. It's highly likely to change as we evaluate usage during the beta. Will look at adding info to the docs.

**Comment by Doa132** [comment]
What is the hourly rate-limit?

**Comment by CyberiumShadow** [comment]
> What is the hourly rate-limit? 

At the moment, it seems to be 1000 requests globally per access token per hour

**Comment by offtheball03** [comment]
Yeah, that messed me up. I'm working on a web-based project, and apparently refreshed too many times. When I got confused about what was happening, I started refreshing and made it worse, because the only place I can see that documented is in this issue right here.

**Comment by markbrown4** [comment]
Will expose the hourly limit in the 429 error response message and also document the `X-RateLimit-Remaining` header.
Thanks for raising!
