### ISSUE TITLE
transferAccount relationship not populated for "Quick save transfer to ..." or round ups

### ISSUE THREAD

**Issue by daveallie** [up-banking/api#80]
Following #66, it looks like there are a few transaction types that don't have the `transferAccount` relationship populated.

- 'Quick save transfers' (swiping down on activity screen with a round ups configured)
  -  `transferAccount` isn't set on either side of the transfer
- Round ups
  - The round up transaction in the enabled saver doesn't have `transferAccount` set
  - Additionally, there's no way to determine which saver the roundup amount went to when looking at the transaction with a round up data.
    - I don't really know where this data should sit (either under the `roundUp` key, or under a different relationship key), it doesn't affect my specific use case, but can see it being an issue for other API users

**Comment by richwalm** [comment]
+1 Running into this one myself.

**Comment by d11wtq** [comment]
Ooof, sorry, that got auto-closed, but yeah we have a fix for this that should go to prod soon. I'll re-open this until we get confirmation it's resolved.

**Comment by daveallie** [comment]
The rogue `Closes #80` in your commit giving away what you're working on 👀 😂

👏 very excited by this, thanks!

**Comment by daveallie** [comment]
I believe this is also an issue for transfers created as a cover for a transaction (e.g. Covering a $10 purchase, results in a -$10 transaction in the selected saver, and a +$10 transaction in the transactions account, without reference to `transferAccount` in either event).

Will your fix also correct the event for this situation?

**Comment by d11wtq** [comment]
We deployed a fix for this one this morning. I just checked my own data and can confirm it looks like `transferAccount` is correctly populated for Round Ups, Covers & Forwards (should work for Quick Saves, Split Payments etc too).
