### ISSUE TITLE
Is the Personal Access Token provision working?

### ISSUE THREAD

**Issue by johnmee** [up-banking/api#81]
Hello,

1. Via https://api.up.com.au/getting_started I was previously issued a Personal Access Token, which is working.
1. This weekend I attempted to invalidate the token and reissue the token without success.  The old token continues to work.
1. Further, my wife attempted to issue a token to her account without success.
1. User support via the app directed us to this (time insensitive?) form of contact.

Q: Is the token revocation not working generally, or is this a single user issue?
Q: Is the token provision not working generally, or is this a single user issue?

To reproduce:
1. (browser) In a browser (not on the mobile device) navigate to https://api.up.com.au/getting_started
1. (app) In the app (on the mobile device) scan the QR code
1. (app) Displays IP address and asks "confirm"
1. (app) Press "confirm"
1. (app) "access granted" with a button "Got it"

Expected:
1. (browser) to display the new token
2. (api) to reject old token
3. (api) to accept new token

Observed:
1. (browser) No change.
2. (api) continues to accept old token

Reproduction is consistent.  Browsers used were firefox 87.0 both with and without "privacy badger", with and without "incognito mode", also with Chromium 89.0.43893.114.

**Comment by d11wtq** [comment]
Hi @johnmee,

So sorry about that. I just gave it a whirl too and it certainly seems to be broken. We're looking into it and will report back here.

**Comment by d11wtq** [comment]
Hi @johnmee,

Apologies for the delay here. We tracked the issue down to an upgraded external dependency that inadvertently led to a bug on this page. Things should now be up and running smoothly again. Thanks for letting us know about the issue ❤️
