### ISSUE TITLE
Any plans to support an official Ruby wrapper?

### ISSUE THREAD

**Issue by ben-gy** [up-banking/api#82]

**Comment by VeryStrongFingers** [comment]
You should be able to generate a Ruby API client using just the OpenAPI spec - check out https://github.com/OpenAPITools/openapi-generator#overview

**Comment by ben-gy** [comment]
Thanks @VeryStrongFingers - I'm almost done but I can't seem to find a way for the generator to change the internal code from an "OpenapiClient" module to something custom, say "UpBankingService" - any ideas?

**Comment by VeryStrongFingers** [comment]
https://openapi-generator.tech/docs/generators/ruby see `moduleName`, I think that's what you're after
I think it's used by adding an arg of `--additional-properties=moduleName=whatever_you_like``
