### ISSUE TITLE
Access to 2Up transaction data

### ISSUE THREAD

**Issue by lambstrings** [up-banking/api#84]
Hi,

Is there an ETA for access to 2Up transaction data through the API?
I have pinged the accounts endpoint and my 2Up account doesn't show up.

Keep up the good work!

**Comment by gxander85** [comment]
Definitely keen on this too. At bare minimum account balance would be great.

**Comment by hayander** [comment]
Is there any update on this one? Would really help with the way that we budget / keep track

**Comment by vkostakos** [comment]
I would argue that this is a "bug" rather than a "feature request". The UP API is currently returning incomplete data. I would expect that it should return all transactions I can see in via the UP app.

**Comment by brutalspoon** [comment]
Also requesting an update - this is the last bit of my financial data that I'm currently unable to track. Given how fantastic the rest of the UX is (including API access to the personal accounts), it's a shame that this falls flat.

**Comment by Hona** [comment]
+1

**Comment by IAmMadfly** [comment]
+2 (Bump)
Also really want this

**Comment by leeTimothy** [comment]
+1

**Comment by markbrown4** [comment]
Ok folks, the account and transaction data is now available for 2Up.
The only limitation is that you cannot add tags to 2Up transactions(just like in app).

Both accounts currently show with a `display_name` of "Up account".
A fix for that will go out on Monday morning to return "Spending" and "2Up Spending".
