### ISSUE TITLE
Some API documentation is being hidden by menu

### ISSUE THREAD

**Issue by mathewdbutton** [up-banking/api#87]
The left hand menu is obscuring the docs when trying to view anything from [Accounts](https://developer.up.com.au/#accounts) and below

![responsive-docs-having-trouble](https://user-images.githubusercontent.com/1100707/121797675-1b7ef380-cc65-11eb-99ea-07b418c8d423.gif)

**Comment by d11wtq** [comment]
@mathewdbutton thanks heaps for reporting this. Turned out some of our CSS had been accidentally stripped following a dependency update requiring a config change 🤦 Awkward. All fixed now.

**Comment by mathewdbutton** [comment]
I know that feeling, no trouble.
