### ISSUE TITLE
Able to tag Interest, Round up, Covers but unable to view in Insights

### ISSUE THREAD

**Issue by OrganicPepper** [up-banking/api#89]
I've been playing with tagging transactions, and I've discovered that since interest, round up, covers are counted as "transactions", they too can be tagged. This is a cool functionality that can give some fun analytics, however the problem is that they don't seem to appear in the insights. 

I guess there hasn't been a view created for these items in the insights, so the app just isn't able to render them? They appear in the count for the tags, but not in the itemised list. 

As you can see from the screenshots, only 5 transactions appear in the insights, but 14 are listed in the count.

![Screenshot_20210703-111948](https://user-images.githubusercontent.com/69879767/124339954-1c1c0180-dbf5-11eb-95bc-1c252737bdc1.jpg)

![Screenshot_20210703-111942](https://user-images.githubusercontent.com/69879767/124339927-fabb1580-dbf4-11eb-9b58-2614437699f3.jpg)

**Comment by markbrown4** [comment]
Thanks for raising here, the bug here is that you were able to add tags to transactions that are not taggable in the app.
We'll raise a 403 error when you attempt to do this in the future.
> Tags cannot be added to this type of transaction
