### ISSUE TITLE
"Endpoint Tree" for future API endpoints

### ISSUE THREAD

**Issue by lukethacoder** [up-banking/api#9]
I assume you guys already have a roadmap of all the awesome endpoints you plan on adding to the API.

It would be cool if these were publicly visible (gotta build the hype), and even cooler if it was in a similar fashion to your current [product tree](https://up.com.au/tree/).

Mad props to the Up Bank dev team for the spot on API docs. I can't wait to build and see what other developers build.

**Comment by d11wtq** [comment]
Thanks for the feedback @lukethacoder. Taken on board :+1:
