### ISSUE TITLE
Authentication Token Not Working

### ISSUE THREAD

**Issue by bec-hawk** [up-banking/api#92]
I tried to run !curl https://api.up.com.au/api/v1/util/ping \
  -H "Authorization: Bearer $your_access_token" in my Jupyter notebook, with my token, but just get the message {"errors":[{"status":"401","title":"Not Authorized","detail":"The request was not authenticated because no valid credential was found in the Authorization header, or the Authorization header was not present."}]}

I tried getting a new token but it still didn’t work.

**Comment by Mause** [comment]
Did you replace `$your_access_token` with your access token?

**Comment by bentwonk** [comment]
I think the documentation should clarify not only do you need to replace text your_access_token with the token, but also the $ symbol

**Comment by Kofro** [comment]
> I think the documentation should clarify not only do you need to replace text your_access_token with the token but also the $ symbol

Agreed, naturally, I replaced your_access_token, not $your_access_token.

**Comment by d11wtq** [comment]
> I think the documentation should clarify not only do you need to replace text your_access_token with the token, but also the $ symbol

Good feedback, thanks. Will make this change.

**Comment by d11wtq** [comment]
> Good feedback, thanks. Will make this change.

This change was released this morning.
